### ISSUE TITLE
Congratulation

### ISSUE THREAD

**Issue by thomas-mangin** [openbgp/openbgp#1]
For a first release, the code is clean and quite easy to read. I wish you all the best with openbgp. 

It is just unfortunate that a popular open source daemon called "openbgpd" already exists ( http://www.openbgpd.org/ ). You may want to consider another name for your project ( it is not too late ) or at least make sure the daemon is not called the same as openbsd's one.

Oh, and do not do my mistake and use \_\_str\_\_ for anything: like you did with "construct", use a different function to generate string representation of BGP objects.

Best of luck.

**Comment by xiaopeng163** [comment]
hi Thomas 

First I want to thank you! we wrote this project in 2011 within Cisco as an internal project, and at that time I reference your `exabgp`(the version is 1.3.4 :+1: ), your code gave me many many inspirations. And thanks for your advise, I will keep on going.

yes, I can change the daemon name from `openbgpd` to another name. For the project name, I knew there is a project called [openbgpd](http://www.openbgp.org/),  but I also found there are no packages named `openbgp` in pypi,  so I wonder if it is possible for me to keep the package name as openbgp?

And the same issue happened in `openbmp`, our another Python BMP project (It was written during 2013 I think). But almost half a year ago, there is a Cisco guy open sourced one BMP project called [OpenBMP](https://github.com/OpenBMP/openbmp) written in C language. 

So if I want to keep the package name as openbgp or openbmp in github and pypi, is there any problem in future?  I am not familiar with open source policy, please help me.

BR,

Peng Xiao

**Comment by thomas-mangin** [comment]
Hi Peng,

You can not always avoid name clashes as there is not policy. 

But knowing release with a name similar to an existing project with cause you a few issues:
 - people googling will find both project, as openbgpd has been going for a long time are likely to find the wrong answers/project
 - if you software need to be packaged by a openbsd ( I do not think openbgpd is packaged for other os ) then you will have a name clash

Overall it is confusing for the user, hence why it is preferable, nothing more.

Sincerely,

Thomas

**Comment by xiaopeng163** [comment]
thanks, I will think about a new name for our project
